# Generated by Django 5.1.5 on 2025-03-23 18:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazvanie category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoryes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Xron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kreditka', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='operations.books')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='naimenovanie operatsii')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opisaniae opiratsii')),
                ('cost', models.FloatField(verbose_name='stoimost')),
                ('operation_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of operation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='operations.category', verbose_name='Category of operation')),
            ],
            options={
                'verbose_name': 'operatsia',
                'verbose_name_plural': 'operatsii',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='nazvanie producta')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='naimenovanie producta')),
                ('price', models.FloatField(verbose_name='stoimost')),
                ('kolvo_na_sklade', models.TextField(verbose_name=99)),
                ('order', models.ManyToManyField(to='operations.order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('kreditka', models.IntegerField()),
                ('xron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.xron')),
            ],
        ),
    ]
