# Generated by Django 5.1.5 on 2025-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='naimenovanie operatsii')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opisaniae opiratsii')),
                ('cost', models.FloatField(verbose_name='stoimost')),
            ],
            options={
                'verbose_name': 'operatsia',
                'verbose_name_plural': 'operatsii',
                'db_table': 'my_table',
                'ordering': [],
            },
        ),
    ]
