# Generated by Django 5.1.5 on 2025-02-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operation',
            table='my_table1',
        ),
    ]
