# Generated by Django 5.1.5 on 2025-03-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_xron_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.xron'),
        ),
    ]
