# Generated by Django 5.1.5 on 2025-03-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_user_xron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='xron',
        ),
        migrations.AddField(
            model_name='xron',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.user'),
        ),
    ]
